language: node_js
node_js:
  - '12'
services:
  - docker

notifications:
  email: false
  slack:
    rooms:
      secure: UWogAh6p3Au6dF1jKwAUOdzoGgVYC3NUXka2qaeCPHzh5i0He0vgKPHhAZaAzT5oYvylYJ2VycA9qW2oRG9DaFkazH2T7terpC6jde/UZkP9oA8yhyy2jMdmJvJbx1YJdqIYaqf7kIQeVrt09kHH6S5ebVNcpLqfbXIYSgulLSPLyG2Mu0TcXjxdlHxJxkLJIfHoMzLBhQcmbVWk7xcLKaCyMDmxaDxiOTfYRuKWZUQygkhlp6hu6CUK0GrdGB0RhEu9byRZ8KbgyA6Tvrfem8PRcQCjnl9MobH3nd1GeDWRl703qVGUFe31HlaStLUrz9EoCWOicIfWd/0rrfkLXn3TeWgcruMU9Qm//q0CBzB//onOOE2mXV/h5JjjwdlNRVKlvruhyKzgV8qkxspxW7dJSXcPfOr3mhZqQ+YuYxk81dKUUm2xrIo2s/Wwq6h+fuGxOSEXnc6ECQA1ceuMlkwoH6RoUwpL9qFVPsij9KewJUiTURVpDJ47qq9/MI86Krhd44Y1H4HFsrKLYFK8eJqKdGA80LMej1x0RYD8Ga/rxaSP33pbkLu62cL6ySAvtyIlZFTfBX7SktHhirwZtSHuG0eaDyzyDQFGWM53NJtIpK+vWd9B/tJarqhIDcpRytUXi1WX7OAd6vuag8QhMCtLeWoOsqnyUFLbIEQX9MQ=
    on_success: always
    on_failure: always  

script:
  - |
   REPO_SLUG="$TRAVIS_REPO_SLUG"  
   IMAGE_NAME=${REPO_SLUG,,} # to lowercase
   if [[ -z "$TRAVIS_TAG" ]]; then
     IMAGE_TAG=latest
     KRAWLER_TAG=latest
   else
     IMAGE_TAG=$(node -p -e "require('./package.json').version")
     KRAWLER_TAG=$(node -p -e "require('./package.json').peerDependencies['@kalisio/krawler']")
   fi
   docker build --build-arg KRAWLER_TAG=$KRAWLER_TAG -f dockerfile -t $IMAGE_NAME:$IMAGE_TAG .

before_deploy:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  script: docker push $IMAGE_NAME:$IMAGE_TAG
  on:
    all_branches: true